services:
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bolt
    container_name: database
    # network_mode: host
    networks:
      - my-network
    # ports:
    #   - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 20s
      retries: 10
  
  users:
    environment:
    - ADMIN_EMAIL=admin@gmail.com
    - ADMIN_USERNAME=admin
    - ADMIN_PASSWORD=123
    - DB_HOST=db
    - DB_PORT=5432
    - DB_NAME=bolt
    - DB_USER=postgres
    - DB_PASSWORD=postgres

    build: ./
    container_name: users
    # network_mode: host
    networks:
      - my-network
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

networks:
  my-network: